"""migrations

Revision ID: 077ee417d84c
Revises: 287cc9b6ad24
Create Date: 2025-01-06 16:11:02.492315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077ee417d84c'
down_revision: Union[str, None] = '287cc9b6ad24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('application_history', 'status',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Enum('Applied', 'Accepted', 'Rejected', 'ResumeDownloaded', name='statusenum'),
    #            existing_nullable=False)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('application_history', 'status',
    #            existing_type=sa.Enum('Applied', 'Accepted', 'Rejected', 'ResumeDownloaded', name='statusenum'),
    #            type_=sa.INTEGER(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
    pass
